# These are supported funding model platforms
custom: ['https://krist.club/send?to=katpcscili&metadata=message%3DDonation+%28Kristify%29','https://krist.club/send?to=khtsmlh67e&metadata=donate%3Dtrue%3Bdonation%3Dtrue%3Bmessage%3DKristify']
